// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package serverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// FabulaClient is the client API for Fabula service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FabulaClient interface {
	Time(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error)
}

type fabulaClient struct {
	cc grpc.ClientConnInterface
}

func NewFabulaClient(cc grpc.ClientConnInterface) FabulaClient {
	return &fabulaClient{cc}
}

var fabulaTimeStreamDesc = &grpc.StreamDesc{
	StreamName: "Time",
}

func (c *fabulaClient) Time(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error) {
	out := new(TimeResponse)
	err := c.cc.Invoke(ctx, "/fabula.Fabula/Time", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabulaService is the service API for Fabula service.
// Fields should be assigned to their respective handler implementations only before
// RegisterFabulaService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type FabulaService struct {
	Time func(context.Context, *TimeRequest) (*TimeResponse, error)
}

func (s *FabulaService) time(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Time(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/fabula.Fabula/Time",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Time(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterFabulaService registers a service implementation with a gRPC server.
func RegisterFabulaService(s grpc.ServiceRegistrar, srv *FabulaService) {
	srvCopy := *srv
	if srvCopy.Time == nil {
		srvCopy.Time = func(context.Context, *TimeRequest) (*TimeResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Time not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "fabula.Fabula",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Time",
				Handler:    srvCopy.time,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "server.proto",
	}

	s.RegisterService(&sd, nil)
}
