sequenceDiagram
    participant Client
    participant BankA.com
    participant BankB.com
    participant TrueTime

    Client ->> BankA.com: GET /accounts/clientId/balance
    Note over Client, BankA.com: Consistent-Id: e919bb203@clientId<br/>Consistent-Type: optimistic
    alt Permitted
        BankA.com ->> Client: 200 OK
        Note over Client, BankA.com: Consistent-Timestamp: 1565122116462728412<br/>{"balance": 100, "currency": "USD"}
    else
        BankA.com -->> Client: 401 Unauthorized
    end
