sequenceDiagram
    participant Client
    participant BankA.com
    participant BankB.com
    participant TrueTime

    Client ->>+ BankA.com: COMMIT /.well-known/consistent-id/e919bb203@clientId
    alt Locks acquired, no conflicts
        BankA.com ->> Client: 202 Accepted
        Note over Client, BankA.com: Consistent-Timestamp: 1565122116462728694<br/>Consistent-Token: 2f9669ad4879740ce56
    else Conflicts with intervening transaction(s) at BankA.com
        BankA.com ->> Client: 409 Conflict
        opt Clean up
            Client -->> BankB.com: DELETE /.well-known/consistent-id/e919bb203@clientId
        end
    end

    Client ->>+ BankB.com: COMMIT /.well-known/consistent-id/e919bb203@clientId
    alt Locks acquired, no conflicts
        BankB.com ->> Client: 202 Accepted
        Note over Client, BankB.com: Consistent-Timestamp: 1565122116462728694<br/>Consistent-Token: 9c79e8c07e2790bc
    else Conflicts with intervening transaction(s) at BankB.com
        BankB.com ->> Client: 409 Conflict
        opt Clean up
            Client -->> BankA.com: DELETE /.well-known/consistent-id/e919bb203@clientId
        end
    end

    Client ->>+ TrueTime: GET /.well-known/truetime/commitwait
    Note over Client, TrueTime: Consistent-Id e919bb203@clientId<br/>Consistent-Token: 2f9669ad4879740ce56@BankA.com,9c79e8c07e2790bc@BankB.com
    Note right of TrueTime: (wait out epsilon)
    TrueTime ->>- Client: 200 OK
    Note over Client, TrueTime: Consistent-Timestamp: 1565122116483256324<br/>Signature: ...
    
    Client ->> BankA.com: COMMIT /.well-known/consistent-id/e919bb203@clientId
    Note over Client, BankA.com: < TrueTime signed exchange >
    BankA.com ->>- Client : 200 OK
    Client ->> BankB.com: COMMIT /.well-known/consistent-id/e919bb203@clientId
    Note over Client, BankB.com: < TrueTime signed exchange >
    BankB.com ->>- Client: 200 OK
